### ISSUE TITLE
Cannot Use Custom Templates

### ISSUE THREAD

**Issue by dominicbarnes** [FontCustom/fontcustom#148]
Just upgraded to v1.2 from v1.0, and I'm trying to get my project updated accordingly. I've got 1 last issue, which is that I can't seem to use any custom templates. And with no helpful output from fontcustom (#142) I cannot really pinpoint the problem.

I'm running `fontcustom` from a base directory, and I have sub-directories like: `icons/`, (vectors) `templates/` (custom templates) and `font/` (output)

My config appears to be set correctly, it's not anything fancy: (I'll only include relevant parts)

``` yaml
input:
  vectors: icons/
  templates: templates/

output:
  fonts: font/
  css: font/
  preview: font/

templates: [ css, preview ]
```

I have `templates/preview.html`, which is a custom preview page I wrote a while back. When I run `fontcustom compile`, it only uses the "core" `preview.html` template, not my own.

I thought this may be a naming conflict with the core template. However, renaming my template simply leads to fontcustom bailing after loading config, presumably because it can't find the template I've named.

My suspicion is that the `input:templates` config is not being loaded correctly, but I can't be sure. Any help is appreciated, thanks!
