### ISSUE TITLE
Not creating fonts

### ISSUE THREAD

**Issue by rctneil** [FontCustom/fontcustom#152]
Hey,

This is my config:

``` yml
# --------------------------------------------------------------------------- #
# Project Info
#   Default values shown. Learn more about these options by running
#   `fontcustom help` or visiting <http://fontcustom.com>.
# --------------------------------------------------------------------------- #

font_name: icon-font
#css_prefix: icon-
#preprocessor_path: ""
#autowidth: false
#no_hash: false
#debug: false
#quiet: false


# --------------------------------------------------------------------------- #
# Project Paths
#   Relative paths are expanded from PROJECT_ROOT (defaults to the directory
#   where the fontcustom command is run). INPUT and OUTPUT can be strings or
#   hashes or file types / names.
# --------------------------------------------------------------------------- #

#project_root: some/other/place
#manifest: tmp/fontcustom

#input:
vectors: vectors         # required
#  templates: app/assets/fonts/fontcustom/templates

#output:
fonts: /                              # required
#  css: app/assets/stylesheets
#  preview: app/views/styleguide
#  my-custom-template.yml: config


# --------------------------------------------------------------------------- #
# Templates
#   Included in Font Custom:
#     preview, css, scss, scss-rails, bootstrap, bootstrap-scss, bootstrap-ie7,
#     bootstrap-ie7-scss
#   Custom templates should be saved in the INPUT[:templates] directory and
#   referenced by their base file name.
# --------------------------------------------------------------------------- #

#templates: [ scss, preview, my-custom-template.yml ]
```

I am running fontcustom compile from my directory of icon-font and it just tells me it's loaded the config file and then does nothing.

Any ideas?
