### ISSUE TITLE
Custom templates' directory naming

### ISSUE THREAD

**Issue by ricburton** [FontCustom/fontcustom#172]
(Thanks for building FontCustom! I hope it's ok to post this issue here.)

I'm running `fontcustom compile svgs` from the project's directory (called `brand-font`) which looks like this:

```
brand-front/brandfront #output folder for fontcustom
brand-font/fontcustom.yml
brand-font/svgs
```

My `fontcustom.yml` file has the following settings for `output`:

```
output:
  fonts: brandfont/fonts                   # required
  index.html: brandfont

templates: [index.html]
```

I'm expecting the `index.html` file to be generated and added to the `brandfont` directory. However, it ends up in `brandfont/svgs`, which I guess is related to the fact that the template file is within my `svgs` directory in the main project folder. Is there a workaround here? I've experimented with specifying the `inputs` folder and changing directory structure but I can't get it to work—any help would be much appreciated.

Thank you.
