### ISSUE TITLE
Allow compilation without generating font files

### ISSUE THREAD

**Issue by jaydenseric** [FontCustom/fontcustom#241]
I only want Font Custom to generate the custom templates (Sass partials for using the icon font as a direct Base64 embed in the styles) and not the actual font files.

I attempted the following config in `fontcustom.yml`, but it seems it is is compulsory to specify an output path for the font files:

```
font_name: icons
no_hash: true
output:
  _font-icons.scss: ../../../styles
  _icon-font.scss: ../../../styles
templates: [_font-icons.scss, _icon-font.scss]
```

Results in:

```
error  Output paths (assigned as a hash) should have a :fonts key. Check your options.
```

It won't do anything until you add:

```
  fonts: ../
```

My temporary workaround is to manually delete them every compile. It would be awesome if Font Custom would only generate files assigned output paths in the config.

For reference, Base64 output is a pretty new Font Custom feature: #131.
